version: '3.4'

services:
  urlresolvermicroservice:
    image: urlresolvermicroservice:latest
    build:
      context: .
      dockerfile: UrlResolverMicroservice/Dockerfile
    network_mode: bridge