version: '3.4'

services:
  urlresolvermicroservice:
    image: ${DOCKER_REGISTRY-}urlresolvermicroservice
    build:
      context: .
      dockerfile: UrlResolverMicroservice/Dockerfile
    network_mode: bridge